# Generated by Django 3.2.5 on 2021-08-14 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nyuseu', '0004_auto_20200623_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='date_grabbed',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 19, 0, 32, 821409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 19, 0, 32, 821382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='folders',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 19, 0, 32, 799343, tzinfo=utc)),
        ),
    ]
