# Generated by Django 3.2.7 on 2021-09-21 16:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('nyuseu', '0006_auto_20210820_1009'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articles',
            managers=[
                ('articles', django.db.models.manager.Manager()),
            ],
        ),
    ]
