# Generated by Django 3.2.7 on 2021-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyuseu', '0007_alter_articles_managers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articles',
            constraint=models.UniqueConstraint(fields=('feeds', 'title'), name='unique_article'),
        ),
    ]
